ALTER TABLE staff ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE store ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE attendance ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE payroll ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE shift_assignment ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
