CREATE TABLE IF NOT EXISTS store_layouts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id UUID NOT NULL UNIQUE REFERENCES store(id) ON DELETE CASCADE,
    length DOUBLE PRECISION NOT NULL,
    width DOUBLE PRECISION NOT NULL,
    height DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS store_zones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id UUID NOT NULL REFERENCES store(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    x_coord DOUBLE PRECISION NOT NULL,
    y_coord DOUBLE PRECISION NOT NULL,
    z_coord DOUBLE PRECISION NOT NULL,
    capacity INTEGER NOT NULL
);

ALTER TABLE shift_assignment ADD COLUMN IF NOT EXISTS zone_id UUID REFERENCES store_zones(id) ON DELETE SET NULL;
